# Generated by Django 2.1.10 on 2019-08-08 16:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HappyHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=2)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('drinks', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('menu_pdf', models.CharField(max_length=100)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_app.Bar')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_count', models.IntegerField()),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_app.Bar')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_app.User'),
        ),
        migrations.AddField(
            model_name='bar',
            name='features',
            field=models.ManyToManyField(to='hh_app.Feature'),
        ),
        migrations.AddField(
            model_name='bar',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_app.User'),
        ),
        migrations.AddField(
            model_name='bar',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_app.Region'),
        ),
    ]
