# Generated by Django 2.1.10 on 2019-08-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_app', '0002_auto_20190808_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='hh_app.Feature'),
        ),
    ]
