# Generated by Django 2.1.10 on 2019-08-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_app', '0003_auto_20190808_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
